### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by shuang92** [joezuntz/cosmosis-build-standard-library#1]
I found a bug when trying to compile cosmosis standard library on Nersc, following the [non-developer instruction](https://firecrown.readthedocs.io/en/latest/non_developer_installation.html) of firecrown:

`/global/homes/s/shuang92/miniconda3/envs/fc/bin/cosmosis-build-standard-library: line 51: cosmosis-configure: No such file or directory`

I managed to bypass it with adding a line in the cosmosis-build-standard-library script:

`conda activate firecrown_user`

**Comment by joezuntz** [comment]
You should not run cosmosis-build-standard-library on NERSC. I would not recommend using the conda installation method on NERSC, because MPI will not work in that case. I am currently testing a NERSC environment for both cosmosis and firecrown.

**Comment by shuang92** [comment]
> You should not run cosmosis-build-standard-library on NERSC. I would not recommend using the conda installation method on NERSC, because MPI will not work in that case. I am currently testing a NERSC environment for both cosmosis and firecrown.

Thanks! MPI was working for me via conda installation, but only on cori, not on perlmutter. The [NERSC instruction](https://cosmosis.readthedocs.io/en/latest/intro/installation.html#nersc) didn't work for me ("make" failed). Glad to know that a new environment is on the way, and I'm happy to help with testing!
